try {
  window.someNonexistentFunction()
} catch {
  console.log("An error happned!")
}